### PR TITLE
rp fellow application

### PR DESCRIPTION
**Pull request by ronald-bbg**
The fellowship applications page is ready for review, thanks!

### CODE REVIEW

**Comment by will-bbg** [comment]
@ronald-bbg I don't have the time to get to give a detailed review but let's make that Application Process section real text and not an image. 

Use this plugin to connect the cards. It's the same plugin I mentioned a month ago. 

https://github.com/musclesoft/jquery-connections/wiki

**Comment by ecstech-admin** [comment]
@ronald-bbg, other than @will-bbg's comment above, looks good!

**Comment by ronald-bbg** [comment]
Hi Team - The live text boxes and connection lines are now active. You'll notice the large and mobile breakpoints match the figma designs but ipad has 100% widths since the connections have more variability there. 

I can look into creating another branch for ipad to test.

**Review by will-bbg — CHANGES_REQUESTED** [review]
We will need to delete unused images. So let's get rid of the "card-collage-sm/xl.png" images.

**Comment by ecstech-admin** [comment]
Looks good, Ronald!

**Review by ecstech-admin — APPROVED** [review]
Looks good, Ronald!

**Review by ecstech-admin — APPROVED** [review]
Maybe optimize images but otherwise, good to go.

**Review by will-bbg — APPROVED** [review]
👍🏽

**Comment by ronald-bbg** [comment]
uploaded optimized images - this is ready for re-approval for merge, thanks!

**Pull request merged**
