### PR TITLE
bugfix/rp 5771237308/508 fixes

### PR DESCRIPTION
**Pull request by ronald-bbg**
Made 508 fixes to fellowships:

See Monday ticket for fixes made: https://blackberg-group.monday.com/boards/5749055412/pulses/5771237308

Files to review and move to production:

HTML -
fellowship-application/index.html
entrepreneur-residence-fellowship/index.html
fellow/index.html
senior-innovation-fellowship/index.html
index.html

CSS -
_site/assets/css/styles.css

JS -
functions.js
hp-news-render.js
fellowship-news-render.js
json-news-render.js
mustache-fellows-render.js

### CODE REVIEW

**Comment by ronald-bbg** [comment]
removed legacy classnames to address H tag hierarchy and used USWDS classnames

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
On /fellow/index.html, from mustache-fellows-render.js, titles are not being rendered under their name (eg: "2023 Senior Innovation Fellow").

**Review by ecstech-admin — COMMENTED** [review]
The USA Banner doesn't seem to have a hover state like it does on DoE & NCCHI (grey on hover).

Otherwise, approved.

**Review by ecstech-admin — APPROVED** [review]

**Comment by ronald-bbg** [comment]
current hover state matches production - adding a note to troubleshoot usa banner dropdown arrow on hover (gray) - can create a separate bugfix for this issue to merge 508 fixes in this PR (accessibility score on home is at 100)

**Pull request merged**
