### PR TITLE
rp entrepreneurs in residence fellows

### PR DESCRIPTION
**Pull request by ronald-bbg**
Creating PR here for layout and content review. 

I've also merged layout and content fixes from branch 'rp-senior-innovations-fellows'.
(I can continue to merge any further fixes from this branch and resolve any conflicts as needed.)

Pending items (@will-bbg  for vis):

1. 1st row img
2. Collage for ERF

### CODE REVIEW

**Comment by will-bbg** [comment]
Testing slack comment

**Comment by ronald-bbg** [comment]
Test slack comment

**Comment by ronald-bbg** [comment]
hi @ecstech-admin this branch is now ready for approval,  thanks!  Once approved, I can handle the merge.

**Comment by will-bbg** [comment]
@ronald-bbg Let's get this merged

**Pull request merged**
