### PR TITLE
rp js css asset fixes

### PR DESCRIPTION
**Pull request by ronald-bbg**
I made the following changes to Fellowships in this PR:

1) Moved modal code to footer.html and footer-sub.html
2) Removed all references to hide #smDiv5 for the header nav (doesn't exist)
3) Added check for owl carousel calls within functions.js
4) Added USWDS top header dropdown up and down arrows for desktop and mobile
5) Added custom sass fixes in _uswds-theme-custom-styles.scss

### CODE REVIEW

**Review by will-bbg — APPROVED** [review]
👍🏽

**Comment by will-bbg** [comment]
Never mind my approval. I want Jim to take a look.

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
Add aria-label to "Learn More" & "Apply Today!" buttons on home. 
On home page, the fellows photos in the carousel are distorted between 1400px and 1200px (screenshot). Above and below that range, they're fine. Believe there's a fix on the sub pages (alumni carousels)
image

**Comment by ronald-bbg** [comment]
Pending va-website-template repo fixes...

**Comment by ronald-bbg** [comment]
this is ready for approval for console errors fixes

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
Home:
- Add 508 to carousel buttons
- Link text for video

SIF:
- Add 508 to carousel buttons
- Add Alt to SIF fellows

ERF:
- Add 508 to carousel buttons
- Add Alt to SIF fellows

News:
LIghthouse = 100/100/100!!!!! Nice!

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
In Lighthouse, carousel buttons on all pages giving "Values assigned to role="" are not valid ARIA roles."

**Review by ecstech-admin — APPROVED** [review]
Good to go!

**Pull request merged**
