### PR TITLE
rp senior innovation fellows

### PR DESCRIPTION
**Pull request by ronald-bbg**
Updated the following in this branch:

1. SIF Subpage
2. SIF Alumni fellows carousel 
3. SIF Alumni profiles w/ news items

### CODE REVIEW

**Comment by ecstech-admin** [comment]
Looking good!

I still see distorted alumni photos in carousel when at tablet. max-height: 232px; seems to be the culprit
image

**Comment by ronald-bbg** [comment]
Last note fixed and ready for approval!

**Comment by ecstech-admin** [comment]
Awesome! Merge it!

**Review by ecstech-admin — APPROVED** [review]
Good to go

**Pull request merged**
