### PR TITLE
Feature 5961013047 infrastructure fellowships

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

- Added ds_store to git ignore
- Added compress & change files yml
- Copied workflow files
- Checked read/write permissions on remote
- Added tinify_api_key secret
- Checked destination urls (updated dev-sandbox)
- Added pull request template file (merged directly with main before this PR to be able to use this template)

## Related Tickets & Documents
- Monday Task # 5961013047

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized 

## Changed Files in this Pull Request ##
- .github/workflows/changed-files.yml
 - .github/workflows/compress.yml
 - .gitignore
 - .github/workflows/deploy-dev-sandbox.yml

### CODE REVIEW

**Review by will-bbg — CHANGES_REQUESTED** [review]
Please see my comments in the ticket.

**Comment by RyanCrux** [comment]
Updated two deploy scripts. 

Lighthouse URLS point to the fellowship pages (minus the MIT page which we don't control).

Also added two labels to the repo - "image compression" & "ready for review".

**Review by will-bbg — CHANGES_REQUESTED** [review]
I added the label “ready for review” to check the workflows. Looks like the lighthouse job failed. We will need to define index.html file as well. Not just the directory.

**Comment by RyanCrux** [comment]
I resolved the invalid URL error. Current error: 'NoSuchBucket: The specified bucket does not exist'.

thoughts: 
     - Check bucket name in config file (secret) against what you have is AWS console.
OR
    - More likely, because I think you already had this working - the global secret isn't providing the key correctly. Fastest test may be to create the secret at the repo level?

Thoughts?

**Review by will-bbg — APPROVED** [review]
👍🏽

**Pull request merged**
